name: auto_update

permissions: write-all

env:
  TZ: Asia/Shanghai

on:
  workflow_dispatch:
  schedule:
    # 分钟 小时 日期 月份 星期（0-6）//0代表星期天
    - cron: "1 1 * * *"

jobs:
  run-it:
    runs-on: ubuntu-latest
    name: auto_update
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: oven-sh/setup-bun@v2
      - name: auto_update
        shell: bash
        run: |
          set -ex
          cd action
          bun i
          git config --global user.email action@github.com
          git config --global user.name ${{ github.repository_owner }}
          ./auto_update.js
      - name: push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
